### ISSUE TITLE
Refactor prefix in URLs

### ISSUE THREAD

**Issue by Semalexa** [HealthSamurai/ig-ae#15]
`Example: https://healthsamurai.github.io/ig-ae/StructureDefinition/astrazeneca.fhir.ig.ae-Consent-text`

`Let it be: https://healthsamurai.github.io/ig-ae/StructureDefinition/<prefix>Consent-text`

Add 'prefix' to ig.yaml.

**Comment by qdzo** [comment]
Fixed in 0c5d4495e8175b8e890cd08bd0f5b9068a45da49
