### ISSUE TITLE
Wrong context generated for extensions of nested elements

### ISSUE THREAD

**Issue by Semalexa** [HealthSamurai/ig-ae#16]
Should be the full path to the element that we're extending:

```
"context" : [{
    "type" : "element",
    "expression" : "AdverseEvent.suspectEntity.causality"
  }],
```

Examples:

- AdverseEvent-rechallenge.json
- MedicationAdministration-frequency.json

![notepad++_i2dtOa0El6](https://user-images.githubusercontent.com/345535/105847290-0732a680-5fa3-11eb-95fb-4eb75184a7cb.png)

![chrome_0nQMNNOlyQ](https://user-images.githubusercontent.com/345535/105847469-43fe9d80-5fa3-11eb-9014-fe6244830ab8.png)

**Comment by qdzo** [comment]
Fixed by 2aa44aa30d746e3951ab1bd24c3f8827ae335aad
