### ISSUE TITLE
Package download link gives 404

### ISSUE THREAD

**Issue by Semalexa** [HealthSamurai/ig-ae#17]
Package download link gives 404

![chrome_h6FZlq2tRT](https://user-images.githubusercontent.com/345535/106939678-2f7a7d80-66e6-11eb-9c6e-b9f90bdd7ee0.png)
![chrome_Nq7MKKpLfj](https://user-images.githubusercontent.com/345535/106939683-31444100-66e6-11eb-9d3d-663b92475023.png)

**Comment by qdzo** [comment]
Fixed in  78f5f0cf3e8d1075c21de32262df6ad6a2ce8922
